#orion:
#  client:
#    fetch-registry: true
#    self-registration: true
#    heartbeat-rate-sec: 5
#    lease-duration-sec: 15
#    kafka:
#      group-id: ${spring.application.name}
#      trusted-packages: "dev.tiltrikt.orion.api.event"
#      bootstrap-servers: localhost:9092