//file:noinspection GroovyAssignabilityCheck
pluginManagement {
    repositories {
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        mavenLocal()
        maven {
            name "GitLab"
            url "https://git.kpi.fei.tuke.sk/api/v4/projects/68034/packages/maven"
            credentials(HttpHeaderCredentials) {
                name = "Private-Token"
                value = System.getenv("KPI_GITLAB")
            }
            authentication {
                header(HttpHeaderAuthentication)
            }
        }
    }
}

rootProject.name = 'orion'

[
        "orion-client",
        "orion-service",
        "orion-service-api-event-streaming",
        "orion-example:fetch-registry-client",
        "orion-example:self-registration-client",
        "orion-example:api-gateway",


].forEach {
    include it
}

rootProject.children.each { project ->
    {
        setProjectBuildFileName(project)
    }
}

void setProjectBuildFileName(project) {
    project.buildFileName = "${project.name}.gradle"
    project.children.each { subproject ->
        {
            setProjectBuildFileName(subproject)
        }
    }
}