dependencies {
    api project(":orion-service-api-event-streaming")
    api "org.springframework.cloud:spring-cloud-commons"
    api "org.springframework.cloud:spring-cloud-starter-loadbalancer"
    api "org.springframework.boot:spring-boot-starter-web"
    compileOnly "org.springframework.boot:spring-boot-starter-webflux"
    annotationProcessor "org.springframework.boot:spring-boot-configuration-processor"
}