server:
  port: 8084

spring:
  application:
    name: self-registration-client

orion:
  client:
    fetch-registry: false
    self-registration: true
    heartbeat-rate-sec: 5
    lease-duration-sec: 15